# Generated by Django 3.0.5 on 2020-05-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200503_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
