# Generated by Django 3.0.5 on 2020-04-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='security_answer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='security_question',
            field=models.CharField(max_length=200),
        ),
    ]
