# Generated by Django 3.0.5 on 2020-05-01 06:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200501_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
