# Generated by Django 3.0.5 on 2020-04-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200407_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='deweyDecimalSystem',
            field=models.CharField(max_length=3),
        ),
    ]
